name: Deploy Airflow to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          set -e

          echo "===== Updating Code ====="

          cd ~/vehicle-batch-orchestrator

          echo "===== Stopping Containers ====="
          docker compose down

          echo "===== Fixing Permissions ====="
          sudo chown -R ubuntu:ubuntu ~/vehicle-batch-orchestrator

          echo "===== Updating Code ====="
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          echo "===== Starting Containers ====="
          docker compose up -d --build

          echo "===== Waiting for Services ====="

          sleep 20

          docker ps

          echo "===== Airflow Status ====="

          docker compose ps

          echo "===== Deployment Successful ====="

          EOF
